apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: springboot-to-skaffold
build:
  artifacts:
  - image: kwonghung/springboot-to-skaffold
    jib:
      type: maven
  - image: kwonghung/springboot-promethues
    context: ./prometheus
    docker:
      dockerfile: Dockerfile
  - image: kwonghung/springboot-grafana
    context: ./grafana
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
