apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: springboot-to-skaffold
build:
  artifacts:
  - image: docker.io/kwonghung/springboot-to-skaffold
    jib:
      type: maven


deploy:
  kubectl:
    manifests:
    - k8s/*.yaml