apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: springboot-to-skaffold
build:
  artifacts:
  - image: kwonghung/springboot-to-skaffold
    docker:
      noCache: false
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: false
    useBuildkit: true


deploy:
  kubectl:
    manifests:
    - k8s/*.yaml