spring:
  security:
    user:
      name: john
      password: passw0rd

management:
  server:
    address: 0.0.0.0
    port: 8090
  health:
    probes:
      enabled: true
    #livenessstate:    #  enabled: true
    #readinessstate:    #  enabled: true

  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    env:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - env
        - health
        - metrics
        - prometheus