{
 "title": "Simple Dashboard for spring boot",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "No of error request & total request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,status) (increase(http_server_requests_seconds_count{job=\"my-springboot-pods\",outcome!=\"SUCCESS\"}[30s]))",
     "legendFormat": "No of error requests [{{instance}},{{status}}]"
    },
    {
     "expr": "sum by (instance) (increase(http_server_requests_seconds_count{job=\"my-springboot-pods\"}[30s]))",
     "legendFormat": "No of total request [{{instance}}]"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,status) (increase(http_server_requests_seconds_count{job=\"my-springboot-pods\",outcome!=\"SUCCESS\"}[30s])) / on (instance) sum by (instance) (increase(http_server_requests_seconds_count{job=\"my-springboot-pods\"}[30s]))",
     "legendFormat": "Error rate [{{instance}}]"
    }
   ]
  },
  {
   "title": "PODs CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"my-springboot-pods\"}",
     "legendFormat": "CPU usage [{{instance}}]"
    }
   ]
  }
 ]
}